import type { Sale } from './types';

// This defines the columns available in the app.
// The key must be a valid key in the `Sale` type.
export const systemFields: { key: keyof Sale; label: string }[] = [
    { key: "id", label: "ID" },
    { key: "productDescription", label: "Nome do Produto" },
    { key: "item_sku", label: "SKU" },
    { key: "orderNumber", label: "Número do Pedido" },
    { key: "cpf", label: "CPF" },
    { key: "marketplace", label: "Canal de Venda" },
    { key: "auth_name", label: "Conta" },
    { key: "status", label: "Status" },
    { key: "saleDate", label: "Data de Venda" },
    { key: "state_name", label: "Estado" },
    { key: "item_quantity", label: "Qtd." },
    { key: "grossValue", label: "Preço (sem frete)" },
    { key: "total", label: "Total" }, 
    { key: "value_with_shipping", label: "Total (com frete)" },
    { key: "commission", label: "Comissão" },
    { key: "commissionPercentage", label: "Comissão %" },
    { key: "fee", label: "Tarifa" },
    { key: "shippingCost", label: "Custo de Envio" },
    { key: "tax", label: "Imposto" },
    { key: "packaging", label: "Embalagem" },
    { key: "unitCost", label: "Custo Unitário" },
    { key: "totalCost", label: "Custo Total" },
    { key: "product_cost", label: "Custo do Produto" },
    { key: "profit", label: "Lucro" },
    { key: "profitPercentage", label: "Lucro %" },
    { key: "netValue", label: "Valor Líquido" },
    { key: "refundedValue", label: "Valor estornado" },
    { key: "item_image", label: "Imagem do Produto" },
    { key: "paidAmount", label: "Valor Pago" },
    { key: "discount", label: "Desconto" },
    { key: "discountMarketplace", label: "Desconto Marketplace" },
    { key: "deliveryType", label: "Tipo de Frete" },

    // Other potential fields for mapping
    { key: "friendlyName", label: "Nome Amigável" },
    { key: "statusDescription", label: "Descrição do Status" },
    { key: "verified", label: "Verificado" },
    { key: "realStatus", label: "Status Real" },
    { key: "returnStatus", label: "Status Devolução" },
    { key: "verified2", label: "Verificado 2" },
    { key: "ticket", label: "Ticket" },
    { key: "resolved", label: "Resolvido" },
    { key: "notes", label: "Notas" },
    { key: "returnTracking", label: "Rastreio Devolução" },
    { key: "transferForecast", label: "Previsão de Transferência" },
    { key: "transferDate", label: "Data de Transferência" },
    { key: "editedLabel", label: "Etiqueta Editada" },

    // Added fields
    { key: 'customerLastName', label: "Sobrenome do Cliente" },
    { key: 'customerNickname', label: "Apelido do Cliente" },
    { key: 'customerEmail', label: "Email do Cliente" },
    { key: 'documentType', label: "Tipo do Documento" },
    { key: 'phoneAreaCode', label: "DDD" },
    { key: 'phoneNumber', label: "Telefone" },
    { key: 'addressStreet', label: "Rua" },
    { key: 'addressNumber', label: "Número" },
    { key: 'stateAbbreviation', label: "Sigla do Estado" },
    { key: 'countryName', label: "País" },
    { key: 'addressComment', label: "Comentário do Endereço" },
    { key: 'addressReceiverName', label: "Nome do Destinatário" },
    { key: 'addressReceiverPhone', label: "Telefone do Destinatário" },
];
