import type { Sale } from './types';

// This defines the columns available in the app.
// The key must be a valid key in the `Sale` type.
export const systemFields: { key: keyof Sale; label: string }[] = [
    { key: "id", label: "ID" },
    { key: "productDescription", label: "Nome do Produto" },
    { key: "item_sku", label: "SKU" },
    { key: "orderNumber", label: "Número do Pedido" },
    { key: "customer_document", label: "CPF" },
    { key: "marketplace", label: "Canal de Venda" },
    { key: "auth_name", label: "Conta" },
    { key: "status", label: "Status" },
    { key: "date", label: "Data de Venda" },
    { key: "state_name", label: "Estado" },
    { key: "item_quantity", label: "Qtd." },
    { key: "grossValue", label: "Preço (sem frete)" },
    { key: "total", label: "Total" }, 
    { key: "value_with_shipping", label: "Total (com frete)" },
    { key: "fee_order", label: "Comissão" },
    { key: "commissionPercentage", label: "Comissão %" },
    { key: "fee", label: "Tarifa" },
    { key: "fee_shipment", label: "Custo de Envio" },
    { key: "tax", label: "Imposto" },
    { key: "packaging", label: "Embalagem" },
    { key: "unitCost", label: "Custo Unitário" },
    { key: "totalCost", label: "Custo Total" },
    { key: "left_over", label: "Lucro" },
    { key: "profitPercentage", label: "Lucro %" },
    { key: "netValue", label: "Valor Líquido" },
    { key: "refundedValue", label: "Valor estornado" },
    { key: "item_image", label: "Imagem do Produto" },
    { key: "paid_amount", label: "Valor Pago" },
    { key: "discount", label: "Desconto" },
    { key: "discount_marketplace", label: "Desconto Marketplace" },

    // Keeping other fields for potential mapping, but they won't be default.
    { key: "friendlyName", label: "Nome Amigável" },
    { key: "statusDescription", label: "Descrição do Status" },
    { key: "verified", label: "Verificado" },
    { key: "realStatus", label: "Status Real" },
    { key: "returnStatus", label: "Status Devolução" },
    { key: "verified2", label: "Verificado 2" },
    { key: "ticket", label: "Ticket" },
    { key: "resolved", label: "Resolvido" },
    { key: "notes", label: "Notas" },
    { key: "returnTracking", label: "Rastreio Devolução" },
    { key: "transferForecast", label: "Previsão de Transferência" },
    { key: "transferDate", label: "Data de Transferência" },
    { key: "editedLabel", label: "Etiqueta Editada" },
];
